[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
DATASET_CLASSES = ['all']
BATCH_SIZE = 4
NUM_WORKERS = 8
DATA_PREPROCESSED_PATH = ""
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"
OUTPUT_DIR = "/work/grana_maxillo/UNetMerging_output/"

[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = ""
N_EPOCHS_FREEZE = -1

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.0001
HEAD_LR = 0.001
WEIGHT_DECAY = 0.1

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 21
SAVE_EVERY = 10
RESUME = "/work/grana_maxillo/UNetMerging/checkpoints/PretrainExperiment_ciemotpb_pretrain/checkpoint_50_2025-02-09 18:00:05.589000.pth"
