[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ZhimingCui"]
DATASET_CLASSES = ['all']
BATCH_SIZE = 4
NUM_WORKERS = 4
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
COMPILE = false
IN_CHANNELS = 1
DROPOUT_PROB = 0.1
# PRETRAIN_CHECKPOINTS = None

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
LR = 0.001
WEIGHT_DECAY = 0.01

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 100
SAVE_EVERY = 2
RESUME = "/work/grana_maxillo/UNetMergingOutput/PretrainExperiment_ciemotpb_pretrain/checkpoint_50_2025-02-09 18:00:05.589000.pth"
