[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ZhimingCui"]
DATASET_CLASSES = ['all']
BATCH_SIZE = 1
NUM_WORKERS = 2
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
COMPILE = false
IN_CHANNELS = 1

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[TrainConfig]
# ZhimingCui
# RESUME = "/work/grana_maxillo/UNetMerging/checkpoints/PretrainExperiment_kzsmdcc6_pretrain_stable/checkpoint_48_2025-02-09 17:53:31.384283.pth"
# RESUME = "/work/grana_maxillo/UNetMerging/checkpoints/PretrainExperiment_ciemotpb_pretrain/checkpoint_50_2025-02-09 18:00:05.589000.pth"
RESUME = "/work/grana_maxillo/UNetMergingOutput/PretrainExperiment_yg0hhcbw__3ddo_n=2_lr=0.001_batch_size=4_dropout=0.5/checkpoint_50_2025-02-17 14:17:13.066854.pth"

# AMOS
# RESUME = "/work/grana_maxillo/UNetMergingOutput/PretrainExperiment_ki4vnv6n__AMOS_n=0_lr=0.0001_batch_size=8_dropout=0.0/checkpoint_50_2025-02-19 13:00:35.016918.pth"
# RESUME = "/work/grana_maxillo/UNetMergingOutput/PretrainExperiment_93hiiztt__AMOS_n=0_lr=0.001_batch_size=4_dropout=0.5/checkpoint_50_2025-02-19 13:45:36.568554.pth"
# RESUME = "/work/grana_maxillo/UNetMergingOutput/PretrainExperiment_klldc4s2__AMOS_n=1_lr=0.001_batch_size=4_dropout=0.5/checkpoint_50_2025-02-20 11:34:36.243538.pth"