[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
DATASET_CLASSES = []
BATCH_SIZE = 8
NUM_WORKERS = 8
DATA_PREPROCESSED_PATH = ""
DATA_RAW_PATH = "/leonardo_scratch/large/userexternal/gcapitan/data"
OUTPUT_DIR = "/leonardo_scratch/large/userexternal/llumetti/output_UNetMerging/"

[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = ""
N_EPOCHS_FREEZE = 2

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.0001
HEAD_LR = 0.001
WEIGHT_DECAY = 0.1

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 31
SAVE_EVERY = 10
