[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ZhimingCui"]
DATASET_CLASSES = ['all']
BATCH_SIZE = 4
NUM_WORKERS = 8
DATA_PREPROCESSED_PATH = ""
DATA_RAW_PATH = "/leonardo_scratch/fast/IscrB_FeeCO/UNetMerging/data"
OUTPUT_DIR = "/leonardo_scratch/large/userexternal/llumetti/output_UNetMerging/"

[BackboneConfig]
NAME = "ResidualUNet3D"
COMPILE = false
IN_CHANNELS = 1
N_EPOCHS_FREEZE = 0
DROPOUT_PROB = 0.5
F_MAPS = 32

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 32

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.001
HEAD_LR = 0.001
WEIGHT_DECAY = 0.1

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 101
SAVE_EVERY = 25
