[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "/work/grana_maxillo/UNetMerging/checkpoint_325_2025-02-02 01:55:56.247190.pth"
N_EPOCHS_FREEZE = 10

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64