[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = []
DATSET_CLASSES = []
BATCH_SIZE = 1
NUM_WORKERS = 2
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "UNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "/work/grana_maxillo/UNetMerging/checkpoints/checkpoint_190_2025-01-19 04:55:49.994931.pth"

[OptimizerConfig]
NAME = "AdamW"
LR = 0.001
WEIGHT_DECAY = 0.01

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 11
