[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
INCLUDE_ONLY_CLASSES = ['Pharynx']
BATCH_SIZE = 2
NUM_WORKERS = 2
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "UNet3D"
COMPILE = true
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "/work/grana_maxillo/UNetMerging/checkpoints/checkpoint_190_2025-01-19 04:55:49.994931.pth"

[OptimizerConfig]
NAME = "SGD"
LR = 0.1
MOMENTUM = 0.9
WEIGHT_DECAY = 0.0001

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 11
SAVE_EVERY = 10
