[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
INCLUDE_ONLY_CLASSES = ['Left Inferior Alveolar Canal', 'Right Inferior Alveolar Canal']
BATCH_SIZE = 4
NUM_WORKERS = 4
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "/work/grana_maxillo/UNetMerging/checkpoint_325_2025-02-02 01:55:56.247190.pth"
N_EPOCHS_FREEZE = 0

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.001
HEAD_LR = 0.001
WEIGHT_DECAY = 0.01

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 11
SAVE_EVERY = 1