[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
DATASET_CLASSES = ['all']
BATCH_SIZE = 1
NUM_WORKERS = 2
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
COMPILE = false
IN_CHANNELS = 1

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[TrainConfig]
#RESUME = "/work/grana_maxillo/UNetMerging/checkpoints/PretrainExperiment_kzsmdcc6_pretrain_stable/checkpoint_48_2025-02-09 17:53:31.384283.pth"
RESUME = "/work/grana_maxillo/UNetMerging/checkpoints/PretrainExperiment_ciemotpb_pretrain/checkpoint_50_2025-02-09 18:00:05.589000.pth"
