[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
INCLUDE_ONLY_CLASSES = ["Lower Jawbone", "Left Inferior Alveolar Canal", "Right Inferior Alveolar Canal"] 
# INCLUDE_ONLY_CLASSES = ["Lower Jawbone"] 
BATCH_SIZE = 1
NUM_WORKERS = 2
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
COMPILE = false
IN_CHANNELS = 1

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64
