[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["AbdomenCT-1K", "AMOS", "BTCV_Abdomen", "BTCV_Cervix", "SegThor", "TotalSegmentator", "ZhimingCui"]
INCLUDE_ONLY_CLASSES = []
BATCH_SIZE = 6
NUM_WORKERS = 4
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
COMPILE = false
IN_CHANNELS = 1
# PRETRAIN_CHECKPOINTS = None

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
LR = 0.001
WEIGHT_DECAY = 0.01

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 10000
RESUME = "/work/grana_maxillo/UNetMerging/checkpoint_275_2025-01-31 21:36:04.030220.pth"
