[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
INCLUDE_ONLY_CLASSES = [
    "Lower Left Canine",
    "Lower Right Canine",
]
BATCH_SIZE = 4
NUM_WORKERS = 4
DATA_PREPROCESSED_PATH = "/work/grana_maxillo/UNetMergingData/preprocessed_data"
DATA_RAW_PATH = "/work/grana_maxillo/UNetMergingData/raw_data"

[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "/work/grana_maxillo/UNetMerging/checkpoint_325_2025-02-02 01:55:56.247190.pth"
N_EPOCHS_FREEZE = 10

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.00001
HEAD_LR = 0.001
WEIGHT_DECAY = 10

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 51
SAVE_EVERY = 10
