[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"]
DATASET_CLASSES = ['1']
BATCH_SIZE = 4
NUM_WORKERS = 4
DATA_PREPROCESSED_PATH = "/this/should/not/be/used"
DATA_RAW_PATH = "/leonardo_scratch/large/userexternal/gcapitan/data/"

[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "checkpoints/PretrainExperiment_ciemotpb_pretrain/checkpoint_50_2025-02-09 18:00:05.589000.pth"
N_EPOCHS_FREEZE = 2

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.0001
HEAD_LR = 0.001
WEIGHT_DECAY = 0.1

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 21
SAVE_EVERY = 10
