[DataConfig]
NAME = "ComposedDataset"
DATASET_NAMES = ["ToothFairy2"] # ['BTCV_Abdomen']
DATASET_CLASSES = []
BATCH_SIZE = 8
NUM_WORKERS = 8
DATA_PREPROCESSED_PATH = ""
DATA_RAW_PATH = "/path/to/your/data"  # Update this path to your data location
OUTPUT_DIR = "/path/to/your/output/"  # Update this path to your output location

[BackboneConfig]
NAME = "ResidualUNet3D"
IN_CHANNELS = 1
PRETRAIN_CHECKPOINTS = "/path/to/your/pretrained/checkpoint.pth"  # Update this path to your pretrained checkpoint
N_EPOCHS_FREEZE = 2

[HeadsConfig]
NAME = "TaskHeads"
COMPILE = false
IN_CHANNELS = 64

[OptimizerConfig]
NAME = "AdamW"
BACKBONE_LR = 0.0001
HEAD_LR = 0.001
WEIGHT_DECAY = 0.1

[LossConfig]
NAME = "DiceBCELoss"

[TrainConfig]
EPOCHS = 21
SAVE_EVERY = 10
